name: "Set Up Langs"
description: "Set up python and node"
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Display Language Dependency Versions
      shell: bash
      run: |
        python --version
        pip --version
        node --version
        npm --version
